"""Issues dynamic search queries generated by keyword_node via Google News RSS."""
import urllib.parse
import structlog
from collectors.base import BaseCollector, CollectedArticle
from collectors.google_news_rss import GoogleNewsRSSCollector
from database.repositories.continuity_repo import log_keyword, update_keyword_yield

logger = structlog.get_logger()

GOOGLE_NEWS_BASE = "https://news.google.com/rss/search?q={query}&hl={hl}&gl=KR&ceid=KR:{hl}"


class DynamicSearchCollector:
    """Runs LLM-generated keyword queries against Google News and Naver RSS."""

    def __init__(self, run_uuid: str, run_date: str, keywords: list[dict]):
        self.run_uuid = run_uuid
        self.run_date = run_date
        self.keywords = keywords  # [{"query": str, "language": "ko"|"en", "source": str, "rationale": str}]

    async def collect_all(self) -> list[CollectedArticle]:
        all_articles: list[CollectedArticle] = []
        for kw in self.keywords:
            query = kw.get("query", "")
            language = kw.get("language", "ko")
            source_type = kw.get("source", "google_news")
            rationale = kw.get("rationale", "")

            if not query:
                continue

            log_keyword(
                run_uuid=self.run_uuid,
                run_date=self.run_date,
                keyword_query=query,
                language=language,
                source_type=source_type,
                rationale=rationale,
            )

            articles = await self._fetch_query(query, language, source_type)
            update_keyword_yield(self.run_uuid, query, len(articles))
            all_articles.extend(articles)
            logger.info("dynamic_search", query=query[:50], lang=language, found=len(articles))

        logger.info("dynamic_search_total", total=len(all_articles))
        return all_articles

    async def _fetch_query(self, query: str, language: str, source_type: str) -> list[CollectedArticle]:
        ceid = f"KR:{language}"
        url = GOOGLE_NEWS_BASE.format(
            query=urllib.parse.quote(query), hl=language
        )
        collector = GoogleNewsRSSCollector(
            source_id=f"dynamic_{source_type}",
            query=query,
            language=language,
            gl="KR",
            ceid=ceid,
        )
        return await collector.collect()
